#spring.config.import=optional:file:C:\Users\Nitish Kumar\OneDrive\Desktop\S.H.D.E.P_PROJECT\Authentication/.env[.properties]
spring.config.import=optional:file:.env[.properties]

spring.application.name=Authentication

spring.datasource.url=jdbc:postgresql://localhost:5432/microservice

spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.port=8081

# JWT properties
jwt.secret=${JWT_SECRET}

jwt.expiration=3600000
jwt.refreshExpiration=86400000

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true

