# =========================================================
# APPLICATION
# =========================================================
spring.config.import=optional:file:.env[.properties]

spring.application.name=Authentication


# =========================================================
# SERVER
# =========================================================
# Local: 8081
# Render: uses PORT environment variable
server.port=${PORT:8081}

# Render requires the application to be reachable externally
server.address=0.0.0.0
user.service.url=${USER_SERVICE_URL:http://localhost:8082}

# =========================================================
# DATABASE
# =========================================================
# Local default:
# jdbc:postgresql://localhost:5432/microservice
#
# Render:
# Set DB_URL environment variable
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/microservice}

spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver


# =========================================================
# JPA / HIBERNATE
# =========================================================
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=${JPA_SHOW_SQL:true}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# =========================================================
# JWT
# =========================================================
jwt.secret=${JWT_SECRET}

jwt.expiration=${JWT_EXPIRATION:3600000}

jwt.refreshExpiration=${JWT_REFRESH_EXPIRATION:86400000}


# =========================================================
# ACTUATOR / MONITORING
# =========================================================
management.endpoints.web.exposure.include=health,info,metrics

management.endpoint.health.show-details=always

management.endpoint.metrics.enabled=true


# =========================================================
# HEALTH CHECK
# =========================================================
management.endpoint.health.enabled=true
