spring.config.import=optional:file:.env[.properties]

spring.application.name=gateway

# =========================================================
# Server
# =========================================================

server.port=${PORT:8080}
server.address=0.0.0.0


# =========================================================
# Authentication Service
# =========================================================

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**


# =========================================================
# User Service
# =========================================================

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=${USER_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1


# =========================================================
# Order Service
# =========================================================

spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=${ORDER_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.routes[2].predicates[0]=Path=/orders/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1


# =========================================================
# Catalog Service
# =========================================================

spring.cloud.gateway.routes[3].id=catalog-service
spring.cloud.gateway.routes[3].uri=${CATALOG_SERVICE_URL:http://localhost:8085}
spring.cloud.gateway.routes[3].predicates[0]=Path=/catalog/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1


# =========================================================
# Payment Service
# =========================================================

spring.cloud.gateway.routes[4].id=payment-service
spring.cloud.gateway.routes[4].uri=${PAYMENT_SERVICE_URL:http://localhost:8084}
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/payments/**


# =========================================================
# Dashboard Service
# =========================================================

spring.cloud.gateway.routes[5].id=dashboard-service
spring.cloud.gateway.routes[5].uri=${DASHBOARD_SERVICE_URL:http://localhost:8086}
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/dashboard/**,/dashboard/**,/admin/**


# =========================================================
# JWT
# =========================================================

jwt.secret=${JWT_SECRET}


# =========================================================
# Actuator
# =========================================================

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true


# =========================================================
# CORS
# =========================================================

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=${FRONTEND_URL:http://localhost:5173}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true


# =========================================================
# Backend Logging
# =========================================================

logging.level.root=INFO

logging.level.com.auth=INFO
logging.level.com.user=INFO
logging.level.com.ecommerce.catalog=INFO
logging.level.com.orderservice=INFO
logging.level.com.Payment=INFO
logging.level.com.gatway=INFO
logging.level.com.dashboard=INFO