spring.application.name=Authentication

spring.datasource.url=jdbc:postgresql://localhost:5432/microservice
<<<<<<< HEAD
spring.datasource.username=postgres
spring.datasource.password=mtlb kuch bhi @9013
=======
spring.datasource.username= postgres
spring.datasource.password=**** **** ****
>>>>>>> bc6e37b5158a5e6ea073b47570b5a8e16f902ec3

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
<<<<<<< HEAD

server.port=8089

# JWT properties
jwt.secret=mySuperSecretKeyThatIsAtLeast32BytesLong123
jwt.expiration=3600000
jwt.refreshExpiration=86400000
=======
server.port=****
>>>>>>> bc6e37b5158a5e6ea073b47570b5a8e16f902ec3
