spring.config.import=optional:file:.env[.properties]
spring.application.name=Payment

spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

server.port=8084
razorpay.key=${RAZORPAY_KEY}
razorpay.secret=${RAZORPAY_SECRET}
razorpay.webhook-secret=${RAZORPAY_WEBHOOK_SECRET}

# when payment work as consumer then the configuration of kafka are:
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=payment-group

spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.Payment.event.OrderCreatedEvent

# when payment work as producer then the configuration of kafka are:
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=false



# Resilience4j Retry

resilience4j.retry.instances.paymentRetry.max-attempts=3
resilience4j.retry.instances.paymentRetry.wait-duration=2s


# Circuit Breaker

resilience4j.circuitbreaker.instances.paymentCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.sliding-window-size=5
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.wait-duration-in-open-state=20s

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true

