spring.application.name=Payment

spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db
spring.datasource.username= postgres
spring.datasource.password= mtlb kuch bhi @9013
spring.jpa.hibernate.ddl-auto=update

server.port=8084

razorpay.key=test
razorpay.secret=test
razorpay.webhook-secret=test